kind = "go"
version = "1.25.12"
package_name = "aptrepo-go"
package_revision = "1"
package_dependencies = ["libc6"]
download_base = "https://go.dev/dl"
install_prefix = "/opt/aptrepo/go"

[architectures.amd64]
target = "linux-amd64"
sha256 = "234828b7a89e0e303d2556310ee549fbcf253d28de937bac3da13d6294262ac1"

[architectures.arm64]
target = "linux-arm64"
sha256 = "8b5884aef89600aef5b0b051fb971f11f49bb996521e911f30f02a66884f7bd2"
