/** Shape of {baseurl}/index.json (generated by scripts/repo-index.ts). */
export interface RepoPackage {
  name: string;
  description: string;
  homepage?: string;
  /** suite codename → debian version string, e.g. "1.2.0-1~deb12u1" */
  versions: Record<string, string>;
}

export interface RepoIndex {
  origin: string;
  label: string;
  suites: string[];
  components: string[];
  architectures: string[];
  generated_at?: string;
  packages: RepoPackage[];
}
